UPDATE `creature_template` SET `InhabitType` = 2,`speed_walk` = 1.2, `speed_run` = 1.2 WHERE (entry = 48192);
UPDATE `creature` SET `spawndist`=15,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 48192;
UPDATE `creature_template` SET `InhabitType` = 1 WHERE (entry = 48182);
UPDATE `creature_template` SET `InhabitType` = 2 WHERE (entry = 48191);
UPDATE `creature` SET `spawndist`=15,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 48191;
UPDATE `creature_template` SET `InhabitType` = 2 WHERE (entry = 48188);
UPDATE `creature` SET `spawndist`=10,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 48188;
UPDATE `creature_template` SET `InhabitType` = 4 WHERE (entry = 48179);
UPDATE `creature` SET `spawndist`=0,`MovementType` = '0'  WHERE `spawndist` = 0 AND `id` = 48179;
UPDATE `creature_template` SET `InhabitType` = 1 WHERE (entry = 5359);
UPDATE `creature_template` SET `InhabitType` = 2, `movementId` = 0 WHERE (entry = 36047);
UPDATE `creature_template_addon` SET `bytes1` = '0' WHERE `entry` = 36047;
UPDATE `creature` SET `spawndist`=20,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 36047;
UPDATE `creature_template` SET `InhabitType` = 1, `HoverHeight` = 0 WHERE (entry = 12347);
UPDATE `creature_template` SET `HoverHeight` = 0 WHERE (entry = 36068);
UPDATE `creature_template_addon` SET `bytes2` = '0' WHERE `entry` = 36068;
UPDATE `creature` SET `spawndist`=15,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 36068;
UPDATE `creature_template` SET `InhabitType` = 1, `HoverHeight` = 0 WHERE (entry = 3812);
UPDATE `creature_template` SET `InhabitType` = 1, `HoverHeight` = 0 WHERE (entry = 3814);
UPDATE `creature_template` SET `InhabitType` = 2, `HoverHeight` = 0 WHERE (entry = 34350);
UPDATE `creature` SET `spawndist`=10,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 34350;
UPDATE `creature_template` SET `InhabitType` = 2, `HoverHeight` = 0 WHERE (entry = 34351);
UPDATE `creature` SET `spawndist`=10,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 34351;
UPDATE `creature_template` SET `faction` = 103 WHERE (entry = 32928);
UPDATE `creature_template` SET `faction` = 103 WHERE (entry = 33864);
UPDATE `creature_template` SET `faction` = 103 WHERE (entry = 33262);
UPDATE `creature_template` SET `faction` = 103 WHERE (entry = 33277);
UPDATE `creature_template` SET `InhabitType` = 1 WHERE (entry = 44116);
UPDATE `creature_template` SET `InhabitType` = 2, `HoverHeight` = 0 WHERE (entry = 44110);
UPDATE `creature` SET `spawndist`=15,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 44110;
UPDATE `creature_template` SET `InhabitType` = 2, `HoverHeight` = 0 WHERE (entry = 12123);
UPDATE `creature` SET `spawndist`=15,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 12123;

UPDATE `creature_template` SET `InhabitType` = 2, `HoverHeight` = 0 WHERE (entry = 43536);
UPDATE `creature` SET `spawndist`=15,`MovementType` = '1'  WHERE `spawndist` = 0 AND `id` = 43536;
