DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283109 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283109 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283109 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283109 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283109 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281803 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281044 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 280968 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283109 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281803 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281044 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 280968 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283109 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284116 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284897 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281803 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285763 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286016 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285709 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281053 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286017 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281045 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281044 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 280968 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 280976 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286373 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286118 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285756 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285690 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285689 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285578 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285577 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286099 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286089 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286088 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286087 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286719 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286332 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285945 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285944 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285943 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285509 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285223 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285037 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285020 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284770 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284741 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284648 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284647 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284002 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283109 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283031 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282436 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284781 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282405 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282175 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282025 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 269597 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284116 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282439 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286250 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286222 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286221 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286219 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285089 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285028 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284907 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284898 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284897 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284851 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284725 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284724 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284723 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284722 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284711 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284710 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286781 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284627 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284626 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283954 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283953 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283175 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282169 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282158 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282138 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282120 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282023 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282123 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281803 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281858 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281801 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281652 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285288 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285765 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285764 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286291 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282441 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282443 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282511 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285763 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286016 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285738 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285709 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285708 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285762 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284733 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 284732 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283625 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 283623 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282185 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 282013 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281053 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 286017 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 285713 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281047 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281045 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 281044 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 280968 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 280967 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 280976 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 280963 ;
DELETE FROM `world`.`quest_visual_effect` WHERE `quest_visual_effect`.`ID` = 280960 ;

DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1456 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1458 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1462 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1466 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1475 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1477 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1492 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1493 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1498 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1501 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1516 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1533 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1544 ;
DELETE FROM `world`.`instance_template` WHERE `instance_template`.`map` = 1554 ;

DELETE FROM `world`.`creature_addon` WHERE `creature_addon`.`guid` = 46014;
DELETE FROM `world`.`creature_addon` WHERE `creature_addon`.`guid` = 42248;
DELETE FROM `world`.`creature_addon` WHERE `creature_addon`.`guid` = 42248;

UPDATE `world`.`creature` SET `MovementType` = '1' WHERE `creature`.`guid` = 273806;

DELETE FROM`creature_questitem` WHERE `creature_questitem`.`ItemId` = 136579 ;
DELETE FROM `creature_questitem` WHERE `creature_questitem`.`ItemId` = 134107 ;
DELETE FROM `creature_questitem` WHERE `creature_questitem`.`ItemId` = 129917 ;
DELETE FROM `creature_questitem` WHERE `creature_questitem`.`ItemId` = 129916 ;

UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181275;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181276;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 191303;
UPDATE `gameobject_template` SET `type` = 3 WHERE entry = 181277;

DELETE FROM `world`.`creature_queststarter` WHERE `creature_queststarter`.`id` = 46424;
DELETE FROM `world`.`creature_queststarter` WHERE `creature_queststarter`.`id` = 46656;
DELETE FROM `world`.`creature_queststarter` WHERE `creature_queststarter`.`id` = 46768;
DELETE FROM `world`.`creature_queststarter` WHERE `creature_queststarter`.`id` = 46769;
DELETE FROM `world`.`creature_queststarter` WHERE `creature_queststarter`.`id` = 48128;

