UPDATE `world`.`creature` SET `creature`.`MovementType` = '0'  WHERE `MovementType` = '1' AND `spawndist` = 0;

UPDATE `world`.`creature_template_addon` SET `auras` = '167347' WHERE `creature_template_addon`.`entry` = 88835;

UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  76587;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  76702;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  78523;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  79496;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  81458;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  81574;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  82651;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  82890;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  82902;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  82967;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  83465;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  83557;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  84221;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  84306;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  84906;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  85789;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  86255;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  86359;
UPDATE `creature_template` SET `unit_flags` = `unit_flags`|16777216 WHERE entry =  87729;

UPDATE `world`.`creature` SET `spawndist` = '5', `MovementType` = '1' WHERE `creature`.`guid` = 273445;
UPDATE `world`.`creature` SET `spawndist` = '5', `MovementType` = '1' WHERE `creature`.`guid` = 302190;

UPDATE `world`.`creature` SET `equipment_id` = '1' WHERE `creature`.`id` = 77046;
UPDATE `world`.`creature_equip_template` SET `ID` = '1' WHERE `creature_equip_template`.`CreatureID` = 77046 AND `creature_equip_template`.`ID` = 0;
UPDATE `world`.`creature` SET `equipment_id` = '1' WHERE `creature`.`id` = 77104;
UPDATE `world`.`creature_equip_template` SET `ID` = '1' WHERE `creature_equip_template`.`CreatureID` = 77104 AND `creature_equip_template`.`ID` = 0;
UPDATE `world`.`creature` SET `equipment_id` = '1' WHERE `creature`.`id` = 77210;
UPDATE `world`.`creature_equip_template` SET `ID` = '1' WHERE `creature_equip_template`.`CreatureID` = 77210 AND `creature_equip_template`.`ID` = 0;

UPDATE `quest_template` SET `QuestSortID` = 0 WHERE (ID = 10559);

UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_grimrail_mob_bomb_trap' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_grimrail_mob_lava_wave' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_grimrail_mob_ogre_trap' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_grimrail_mob_train' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_grimrail_spawning_trigger' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_archery_target' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_champion_darona' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_gromkar_battlemaster' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_gromkar_chain_master' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_gromkar_deadeye' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_gromkar_deck_hand' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_gromkar_footsoldier' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_gromkar_incinerator' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_gromkar_technician' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_gromkar_technician_deckhand_leader' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_gwarnok' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_hammer_stalker' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_iron_star' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_iron_star_vehicle' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_ironwing_flamespitter' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_laborer_ogron' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_rampaging_clefthoof' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_siege_master_olugar' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_mob_thundering_wandler' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_nokgar_mob_dreadfang' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_nokgar_mob_flameslinger' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_oshir_mob_acid_spit' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_oshir_mob_event' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_oshir_mob_rylak' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_oshir_mob_rylak_dest' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_oshir_mob_wolf' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_oshir_mob_wolf_dest' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_skulloc_mob_koramar' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_skulloc_mob_turret' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_skulloc_mob_zuggosh' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_stunned_cheering_practicing_trigger' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_stunned_cheering_practicing_trigger_second_segement' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_stunned_soldiers_trigger' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_trigger_cannon' ;
UPDATE `world`.`creature_template` SET `ScriptName` = '' WHERE `creature_template`.`ScriptName` =  'iron_docks_trigger_stand_third_event' ;

UPDATE `world`.`gameobject_loot_template` SET `Chance` = '100' WHERE `gameobject_loot_template`.`Entry` = 214388 AND `gameobject_loot_template`.`Chance` = 0;

UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 1777325;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 79852;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 798523;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 80805;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 808055;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 808056;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 80816;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 808166;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 808167;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 81305;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 813055;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 813056;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 83612;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 836122;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 836123;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 83613;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 836133;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 836134;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 83616;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 836166;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 836167;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 86231;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 862311;
UPDATE `creature_template` SET `flags_extra` = 0 WHERE entry = 862312;

UPDATE `creature_template` SET `MovementType` = 0 WHERE (entry = 16221);
UPDATE `creature_template` SET `MovementType` = 0 WHERE (entry = 16330);

UPDATE `world`.`creature` SET `zoneId` = '0', `areaId` = '0', `PhaseId` = '170', `PhaseGroup` = '0' WHERE `creature`.`guid` = 21070196;

DELETE FROM `world`.`gameobject_queststarter` WHERE `gameobject_queststarter`.`id` = 232398 AND `gameobject_queststarter`.`quest` = 33111;
DELETE FROM `world`.`gameobject_queststarter` WHERE `gameobject_queststarter`.`id` = 232398 AND `gameobject_queststarter`.`quest` = 34674;
DELETE FROM `world`.`gameobject_queststarter` WHERE `gameobject_queststarter`.`id` = 232398 AND `gameobject_queststarter`.`quest` = 34676;
DELETE FROM `world`.`gameobject_queststarter` WHERE `gameobject_queststarter`.`id` = 232398 AND `gameobject_queststarter`.`quest` = 35459;
DELETE FROM `world`.`gameobject_queststarter` WHERE `gameobject_queststarter`.`id` = 232398 AND `gameobject_queststarter`.`quest` = 35556;
DELETE FROM `world`.`gameobject_queststarter` WHERE `gameobject_queststarter`.`id` = 232398 AND `gameobject_queststarter`.`quest` = 36951;
DELETE FROM `world`.`gameobject_queststarter` WHERE `gameobject_queststarter`.`id` = 232398 AND `gameobject_queststarter`.`quest` = 36951;
DELETE FROM `world`.`gameobject_queststarter` WHERE `gameobject_queststarter`.`id` = 232398 AND `gameobject_queststarter`.`quest` = 36951;
UPDATE `gameobject_template` SET `type` = 2 WHERE (entry = 1557);
UPDATE `gameobject_template` SET `type` = 2 WHERE (entry = 1586);

UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014709;
UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014716;
UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014719;
UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014721;
UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014725;
UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014730;
UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014733;
UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014734;
UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014735;
UPDATE `world`.`gameobject` SET `map` = '1190' WHERE `gameobject`.`guid` =  21014736;

DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21020634;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026576 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026577 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026578 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026579 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026580 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026581 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026582 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026583 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026584 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026585 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21026586 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027672 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027673 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027674 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027675 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027676 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027677 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027678 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027679 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027680 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027681 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027682 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027683 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027684 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027685 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027686 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027687 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027688 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027689 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027690 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027691 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027692 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027693 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027694 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027695 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027696 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027697 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027698 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027699 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027700 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027701 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027702 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027703 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027704 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027705 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027706 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027707 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027708 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027709 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027710 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027711 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027712 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027713 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027714 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21027715 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029686 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029687 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029740 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029741 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029742 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029743 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029744 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029745 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029746 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029747 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21029748 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034132;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034133;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034134;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034135;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034136;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034137;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034138;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034139;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034140;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034141;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034142;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034143;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034144;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034145;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034146;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034147;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034148;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034149;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034150;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034151;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034152;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034153;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034154;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034155;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034156;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034157;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034158;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034159;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034160;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034161;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034162;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034163;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034164;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034165;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034166;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034167;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034168;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034169;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034170;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034171;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034172;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034173;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034174;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034175;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21034176;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21036248 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21036249 ;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21044462;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21044463;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21044514;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21044528;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  21044551;
DELETE FROM `world`.`gameobject` WHERE `gameobject`.`guid` =  210721;

DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  76587;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  76702;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  78523;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  79496;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  81458;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  81574;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  82651;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  82890;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  82902;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  82967;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  83465;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  83557;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  84221;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  84306;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  84906;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  85789;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  86255;
DELETE FROM `world`.`creature_template_addon` WHERE `creature_template_addon`.`entry` =  87729;

UPDATE `world`.`gossip_menu_option` SET `option_icon` = '1' WHERE `gossip_menu_option`.`menu_id` =  13580 AND `gossip_menu_option`.`id` =  0 ;
UPDATE `world`.`gossip_menu_option` SET `option_icon` = '1' WHERE `gossip_menu_option`.`menu_id` =  13790 AND `gossip_menu_option`.`id` =  0 ;
UPDATE `world`.`gossip_menu_option` SET `option_icon` = '1' WHERE `gossip_menu_option`.`menu_id` =  13897 AND `gossip_menu_option`.`id` =  0 ;
UPDATE `world`.`gossip_menu_option` SET `option_icon` = '1' WHERE `gossip_menu_option`.`menu_id` =  14315 AND `gossip_menu_option`.`id` =  0 ;
UPDATE `world`.`gossip_menu_option` SET `option_icon` = '1' WHERE `gossip_menu_option`.`menu_id` =  14649 AND `gossip_menu_option`.`id` =  8 ;
UPDATE `world`.`gossip_menu_option` SET `option_icon` = '1' WHERE `gossip_menu_option`.`menu_id` =  18536 AND `gossip_menu_option`.`id` =  0 ;

